apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaConnector
metadata:
  name: s3-connector
  namespace: myproject
  labels:
    strimzi.io/cluster: my-connect
spec:
  class: org.apache.camel.kafkaconnector.aws2s3.CamelAws2s3SinkConnector
  tasksMax: 1
  config:
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: org.apache.kafka.connect.storage.StringConverter
    topics: fluent-bit-logs
    camel.sink.path.bucketNameOrArn: fluent-bit-logs-bucket
    camel.sink.endpoint.keyName: ${date:now:yyyyMMdd-HHmmssSSS}-${exchangeId}
    # Camel aggregator settings
    camel.beans.aggregate: '#class:org.apache.camel.kafkaconnector.aggregator.StringAggregator'
    camel.aggregation.size: 1000
    camel.aggregation.timeout: 5000
    camel.component.aws2-s3.accessKey: ${file:/opt/kafka/external-configuration/aws-credentials/aws-credentials.properties:aws.access-key}
    camel.component.aws2-s3.secretKey: ${file:/opt/kafka/external-configuration/aws-credentials/aws-credentials.properties:aws.secret-key}
    camel.component.aws2-s3.region: ${file:/opt/kafka/external-configuration/aws-credentials/aws-credentials.properties:aws.region}
